# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: a5680962b896d9cd0aa8672243848f9c
  secret_key: d524ea0e22b900fc609683c75234c7d7
  canvas_page_name: trr
  callback_url: 
  pretty_errors: true
  set_asset_host_to_callback_url: false

test:
  api_key: a5680962b896d9cd0aa8672243848f9c
  secret_key: d524ea0e22b900fc609683c75234c7d7
  canvas_page_name: trr
  callback_url:

production:
  api_key: a5680962b896d9cd0aa8672243848f9c
  secret_key: d524ea0e22b900fc609683c75234c7d7
  canvas_page_name: 
  callback_url:
  pretty_errors: true
  set_asset_host_to_callback_url: false
  
    